### ISSUE TITLE
Make it possible to decode enums

### ISSUE THREAD

**Issue by sgielen** [csirtgadgets/google-protocolbuffers-perl#12]
At this moment, it's possible to define an enum and go from its constants to its int values. However, it would be nice if it were possible to convert a decoded int back to the string constant for printing. At the moment there is a workaround using Symbol::Tables:

``` perl
my $st = Symbol::Tables->New("CODE", "EnumName");
my %type_to_str;
foreach(keys %$st) {
  $type_to_str{$st->{$_}->()} = $_;
}
```

Then, `$type_to_str{5} = "YOUR_CONSTANT"`.

**Comment by wesyoung** [comment]
more than happy to accept PR's!
