### ISSUE TITLE
Strange META.yml contents

### ISSUE THREAD

**Issue by eserte** [csirtgadgets/google-protocolbuffers-perl#13]
The first element of the author array looks strange, see here: https://metacpan.org/source/SAXJAZMAN/Google-ProtocolBuffers-0.11/META.yml#L4

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/google-protocolbuffers-perl/pull/22 -- sorry, notifications from GH were messed up, didn't see this. ty!
