### ISSUE TITLE
MYMETA should not be included

### ISSUE THREAD

**Issue by chorny** [csirtgadgets/google-protocolbuffers-perl#17]
Your distribution (SAXJAZMAN/protobuf/Google-ProtocolBuffers-0.11.tar.gz) contains files MYMETA.yml and/or MYMETA.json. These files should not be included into distribution - they are generated when installing.
See http://weblog.bulknews.net/post/44251476706/stop-shipping-mymeta-to-cpan

P.S. If this report is about old version, please delete old indexed versions mentioned here: http://cpanold.chorny.net/?a=SAXJAZMAN and contact me.

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/google-protocolbuffers-perl/pull/22 -- sorry, notifications from GH were messed up, didn't see this. ty!
