### ISSUE TITLE
Don't ship Makefile to CPAN

### ISSUE THREAD

**Issue by robn** [csirtgadgets/google-protocolbuffers-perl#18]
The current release (0.11) has a Makefile with a more recent timestamp than Makefile.PL. This causes (at least) make-based build systems (eg `dh-make-perl`) to not try to rebuild it, causing the whole build to fail.

The Makefile is pretty much not going to work anywhere other than your own system. There's no good reason to bundle it.

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/google-protocolbuffers-perl/pull/22 -- sorry, notifications from GH were messed up, didn't see this. ty!
