### ISSUE TITLE
dies, unless an optional uint64 field is commented out of the protocol definition

### ISSUE THREAD

**Issue by jbardu** [csirtgadgets/google-protocolbuffers-perl#20]
A binary block that is decoded ok using the current python protocol library, causes Google::ProtocolBuffers to go off the rails, right after decoding a uint64 primitive field that is optional.
  "optional uint64 FieldName = 2;" 
FieldName is not shown in the decoded output of a python run, on the same binary block.

Commenting out the field from the protocol spec results in the same binary being parsed correctly.
I'm unable to work out why :(

**Comment by wesyoung** [comment]
more than happy to accept PR's!
