### ISSUE TITLE
The 0.12 release breaks other CPAN distributions

### ISSUE THREAD

**Issue by eserte** [csirtgadgets/google-protocolbuffers-perl#24]
The following CPAN distributions have failing test suites if used with Google-ProtocolBuffers-0.12:
- DAMS/AnyEvent-Riak-0.93.tar.gz
- RGE/Net-Riak-0.1702.tar.gz
- DAMS/Riak-Client-1.96.tar.gz
- EXUSSUM/Voldemort-0.11.tar.gz

The failing test log always includes something like this:

```
Can't use string ("1") as an ARRAY ref while "strict refs" in use at /home/cpansand/.cpan/build/2016100115/Google-ProtocolBuffers-0.12-1/blib/lib/Google/ProtocolBuffers.pm line 308.
```

**Comment by mark-5** [comment]
Google-ProtocolBuffers-0.12 also breaks MAF/Mesos-1.07.1 . Looks like the new release in not backwards compatible with old generated message classes.
