### ISSUE TITLE
parse error "Unknown syntax"

### ISSUE THREAD

**Issue by martinthurn** [csirtgadgets/google-protocolbuffers-perl#28]
When I call parse() it just prints the following error and dies.  Even if I specify generate_code.  I'm attaching my .proto file.  
[MyMessage.proto.txt](https://github.com/csirtgadgets/google-protocolbuffers-perl/files/2498218/MyMessage.proto.txt)
How can I debug this?  

Unknown syntax at (eval 76) line 13393, <> chunk 1.

**Comment by ken-i** [comment]
Syntax of the Perl module only supports `proto2` - not `proto3`.

See the Perl module `./Google/ProtocolBuffers/Compiler.pm` has the code to indicate `proto2` only:
```
syntax      :   "syntax" "=" strLit ## syntax = "proto2";
                { 
                    die "Unknown syntax" unless $item{strLit} eq 'proto2';
                    $return = '';
                }
```

**Comment by martinthurn** [comment]
That's too bad.  You should probably mention that little detail in the main module pod documentation and/or README
